version: 2.1

orbs:
  rebar3: tsloughter/rebar3@dev:cover

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - rebar3/compile
      - rebar3/xref:
          requires:
            - rebar3/compile
      - rebar3/dialyzer:
          requires:
            - rebar3/compile
      - rebar3/ct:
          cover: true
          requires:
            - rebar3/compile
